<?xml version="1.0"?>
<package format="3">
  <name>fr3_dual_arm_sim</name>
  <version>0.0.1</version>

  <description>FR3 Dual Arm Simulation</description>

  <maintainer email="ratul@example.com">Ratul</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>franka_description</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>action_msgs</exec_depend>
  

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>